FROM golang:1.6.2-alpine
MAINTAINER Kazumichi Yamamoto <yamamoto.febc@gmail.com>

RUN set -x && apk add --no-cache git make bash zip build-base gcc
RUN go get -u github.com/kardianos/govendor

ADD . $GOPATH/src/github.com/dwrap/cli

WORKDIR $GOPATH/src/github.com/dwrap/cli
CMD ["make"]
